services:
  sensor-web:
    container_name: sensor-web
    image: ghcr.io/shipi1/sensor-web:latest
    ports:
      - "3001:3001"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true
